#define NUM_MAX_WEAPON			10
#define NUM_MAX_ENEMY			5
#define NUM_WAVE_INBATTLE		10
#define NUM_MAX_SKILL			50
#define NUM_MAX_CASTLE_LEVEL	11
#define NUM_MAX_BACKGROUND		20

#define WEAPON_ACHER_POSX		145
#define WEAPON_ACHER_POSY		350
#define WEAPON_FIRE_MAGE_POSX		155
#define WEAPON_FIRE_MAGE_POSY		200
#define WEAPON_CANNON_POSX			65
#define WEAPON_CANNON_POSY			270
#define WEAPON_ELECTRIC_POSX		247
#define WEAPON_ELECTRIC_POSY		250
#define WEAPON_FROST_MAGE_POSX		224
#define WEAPON_FROST_MAGE_POSY		150
#define WEAPON_TWIN_POSX			60
#define WEAPON_TWIN_POSY			150
#define WEAPON_HOLY_POSX			395
#define WEAPON_HOLY_POSY			250
#define WEAPON_DARKNESS_POSX		155
#define WEAPON_DARKNESS_POSY		100
#define WEAPON_DRAGON_POSX			200
#define WEAPON_DRAGON_POSY			540
#define WEAPON_CHIMERA_POSX			344
#define WEAPON_CHIMERA_POSY			190

#define ROAD_POSY				(580)

#define ENEMY_TARGETX			210
#define ENEMY_TARGETY			560

#define NUM_MAX_ENEMY			500
#define NUM_MAX_HERO			50

#define WEAPON_ARCHER			0
#define WEAPON_FIRE_MAGE		1
#define WEAPON_CANNON			2
#define WEAPON_ELECTRIC			3
#define WEAPON_FROST_MAGE		4
#define WEAPON_TWIN				5
#define WEAPON_HOLY				6
#define WEAPON_DARKNESS			7
#define WEAPON_DRAGON			8
#define WEAPON_CHIMERA			9
#define WEAPON_CASTLE			10

#define HERO_ID_PALADIN				1
#define HERO_ID_ARCHER				2
#define HERO_ID_FIRE_MAGE			3
#define HERO_ID_BEAST_MASTER		4
#define HERO_ID_ELECTRIC_MAGE		5
#define HERO_ID_ACHEMIST			6
#define HERO_ID_ROBOT				7
#define HERO_ID_CAT_NINJA			8
#define HERO_ID_WOLF_RANGER			9
#define HERO_ID_SANTA				10

#define PET_ID_BIRD				1

#define HEROES_UNLOCK_TYPE_NORMAL					0
#define HEROES_UNLOCK_TYPE_EVENT_XMAS				1
#define HEROES_UNLOCK_TYPE_EVENT_ACHEMIST			2
#define HEROES_UNLOCK_TYPE_EVENT_DAILY_REWARD		3


#define EVENT_TIME_MONTH_XMAS			12
#define EVENT_TIME_DAY_XMAS				31

#define EVENT_TYPE_XMAS						0
#define EVENT_TYPE_ACHEMIST					1
#define EVENT_TYPE_AVAILABLE				EVENT_TYPE_ACHEMIST
#define EVENT_HERO_ID_AVAILABLE				HERO_ID_ACHEMIST
#define EVENT_HERO_NAME_AVAILABLE			"Dr.Brown"
#define EVENT_HERO_UNLOCK_TYPE_AVAILABLE	HEROES_UNLOCK_TYPE_EVENT_ACHEMIST


#define NUM_MAX_HERO_INBATTLE		3

#define DESIGN_GENERAL_POWER_SKILL_REGEN		0
#define DESIGN_GENERAL_COIN_START				1
#define DESIGN_GENERAL_GEM_START				2
#define DESIGN_GENERAL_NUM_TAP_BAR				4
#define DESIGN_GENERAL_TIME_AUTO_ATTACK			5
#define DESIGN_GENERAL_X_CRITICAL				6
#define DESIGN_GENERAL_AUTO_ATTACK_SPEED		7
#define DESIGN_GENERAL_FAIRY_INIT				8
#define DESIGN_GENERAL_FAIRY_TIME				9
#define DESIGN_GENERAL_FAIRY_NUM_TAP			11
#define DESIGN_GENERAL_COST_UNLOCK_HERO			10
#define DESIGN_GENERAL_HOLY_SLAM_PERCENT		12
#define DESIGN_GENERAL_SLOW_TIME				13
#define DESIGN_GENERAL_STUN_TIME				14
#define DESIGN_GENERAL_CHIMERA_TOR_PER			15
#define DESIGN_GENERAL_CHIMERA_TOR_DMG			16

#define HEROBUTTON_TYPE_ATTACK			0
#define HEROBUTTON_TYPE_SKILL			1
#define HEROBUTTON_TYPE_AUTO			2

#define MAX_POWER_NUM_TAP				(((TDGame*)CGame::_this->_current_game)->GetDesignGeneralInfo(DESIGN_GENERAL_NUM_TAP_BAR))
#define MAX_POWER_SKILL					((TDGame*)CGame::_this->_current_game)->GetDesignGeneralInfo(DESIGN_GENERAL_POWER_SKILL_REGEN)

#define EFFECT_HP_LOST_TYPE_NORMAL		0
#define EFFECT_HP_LOST_TYPE_CRITICAL	1
#define EFFECT_HP_LOST_TYPE_CASTLE		2

#define GAME_DEBUG						0
#define GAME_DEBUG_BATTLE_FIX			80

#define INGAME_MENU_ITEM_HEIGHT			145
#define NUM_MAX_ITEM_SHOP				11
#define NUM_MAX_ITEM_RELICS				200

#define HEROES_ICON_SIZE				116
#define NUM_MAX_BOX_ITEM				9

#define TYPE_RENDER_FRAME				0
#define TYPE_RENDER_ANIM				1

#define BOX_ITEM_WIDTH				180
#define BOX_ITEM_HEIGHT				170

#define CASTLE_MAX_LEVEL			10

#define TUTORIAL_TEXT_POSX			125
#define TUTORIAL_TEXT_POSY			515

#define DAILY_QUEST_GROUP_BATTLE_FINISH			1
#define DAILY_QUEST_GROUP_KILL_MONSTER			2
#define DAILY_QUEST_GROUP_NUM_TAP				3
#define DAILY_QUEST_GROUP_USE_AUTO_ATT			4
#define DAILY_QUEST_GROUP_USE_SKILL				5
#define DAILY_QUEST_GROUP_COIN_COLLECT			6

#define IAP_STARTER_TIME			(72*60*60)
#define WHEEL_TIME_RESET			(3*60*60)
#define IAP_DISCOUNT_TIME			(1*60*60)
#define WATCH_ADS_NEXT_TIME1		(5*60)
#define WATCH_ADS_NEXT_TIME2		(10*60)

#define WATCH_ADS_REWARD_TYPE_GEM			0
#define WATCH_ADS_REWARD_TYPE_COIN			1
#define WATCH_ADS_REWARD_TYPE_AUTO_ATT		2
#define WATCH_ADS_REWARD_TYPE_AUTO_SKILL	3
#define WATCH_ADS_REWARD_TYPE_DOUBLE_COIN	4

#define WHEEL_BATTLE_START				1
#define NUM_MAX_HERO_VERSION_1			7
#define NUM_MAX_BATTLE_VERSION_1		100
#define NUM_MAX_BATTLE_VERSION_2		200
#define NUM_MAX_BATTLE_VERSION_3		250
#define NUM_MAX_BATTLE_VERSION_4		500

#define NUM_MAX_BATTLE                  NUM_MAX_BATTLE_VERSION_4

#define NUM_FRAME_AUTO_REFILL_ATTACK	120

#define SHOP_ID_AUTO_ATT			6
#define SHOP_ID_AUTO_SKILL			7
#define SHOP_ID_DOUBLE_COIN			8
#define SHOP_ID_OPEN_BOX			9
#define SHOP_ID_STARTER_PACK		10
#define SHOP_ID_WATCH_ADD			11
#define SHOP_ID_REFILL_HP_CASTLE	12
#define SHOP_ID_FOLLOW_TW			13
#define SHOP_ID_LIKE_FB				14
#define SHOP_ID_RESTORE				15
#define SHOP_ID_DOWN_MOREGAME		16
#define SHOP_ID_GEM_10_99           4

#define HERO_TAG_ID_INPUT_CODE			100

#define IAP_STARTER_TIME_DOUBLE_COIN		2*60*60

#define DIALOG_CONTEXT_WHEEL_REWARD			0
#define DIALOG_CONTEXT_WATCH_ADS			1
#define DIALOG_CONTEXT_TW_FOLLOW			2
#define DIALOG_CONTEXT_FB_LIKE				3
#define DIALOG_CONTEXT_NO_NETWORK			4
#define DIALOG_CONTEXT_RATE_US				5
#define DIALOG_CONTEXT_100_BATTLE			6
#define DIALOG_CONTEXT_INVITATION			7
#define DIALOG_CONTEXT_INVITATION_CONFIRM	8
#define DIALOG_CONTEXT_INVITATION_MESSAGE	9
#define DIALOG_CONTEXT_INVITATION_EXIT      10
#define DIALOG_CONTEXT_INVITATION_GIFT_1	11
#define DIALOG_CONTEXT_INVITATION_GIFT_2	12
#define DIALOG_CONTEXT_INVITATION_GIFT_3	13
#define DIALOG_CONTEXT_DOWN_MOREGAME        14
#define DIALOG_CONTEXT_OFFLINE_REWARD1			15
#define DIALOG_CONTEXT_OFFLINE_REWARD2			16
#define DIALOG_CONTEXT_OFFLINE_REWARD3			17
#define DIALOG_CONTEXT_OFFLINE_REWARD4			18
#define DIALOG_CONTEXT_CONFIRM_NOTIFY			19
#define DIALOG_CONTEXT_WARNING_HACKER			20
#define DIALOG_CONTEXT_DAILY_REWARD				21
#define DIALOG_CONTEXT_CONFIRM_LOADDATA         22
#define DIALOG_CONTEXT_CONFIRM_BUY_IAP	         23
#define DIALOG_CONTEXT_IAP_DISCOUNT_SPEC         24
#define DIALOG_CONTEXT_IAP_DISCOUNT_OFF	         25
#define DIALOG_CONTEXT_REWARD_EARNING_OFF         26
#define DIALOG_CONTEXT_PRESTIGE			         27
#define DIALOG_CONTEXT_VIEW_PRESTIGE			 28
#define DIALOG_CONTEXT_REVIVE_BY_ADS			 29
#define DIALOG_CONTEXT_REVIVE_BY_GEM			 30
#define DIALOG_CONTEXT_RELIC_SPECIAL			 31
#define DIALOG_CONTEXT_PURCHASE_MORE_WHEEL		 32
#define DIALOG_CONTEXT_OFFLINE_EARNING_PRO		 33

#define FB_LIKE_REWARD				1
#define TW_FOLLOW_REWARD			1
#define RATE_US_REWARD				5
#define DOWN_MOREGAME_REWARD        3


#define HERO_SKILL_NIJA_X_HP				1

#define PROCESSING_TIME_OUT				10*6;
#define EVENT_INVITE_CODE_LENGTH        6

#define EVENT_INVITE_REWARD_COIN		20000
#define EVENT_INVITE_REWARD_GEM			5
#define DOWN_MOREGAME_TIME				24*60*60;
#define DOWN_MOREGAME_TRIGGER_BATTLE    14
#define DEFINE_MASTER_IOS       "i6"

#define DAILY_REWARD_TRIGGER_BATTLE			0
#define DAILY_REWARD_TYPE_COIN				1
#define DAILY_REWARD_TYPE_GEM				2
#define DAILY_REWARD_TYPE_RELIC				3
#define DAILY_REWARD_TYPE_BIG				4
#define DAILY_REWARD_TYPE_HERO				5

//quoc.nguyen
#define TIME_BUY_OPEN_BOX                   (3*60)
#define TIME_SHOWADS_ARCHIVE				(5*60)
#define BATTLE_START_SHOWADS				5
//#define ANDROID_RATE_REWARD		

#define NOTIFICATION_MAX		50
#define RELIC_PRESTIGE_ADD_DMG_BASIC		0
#define MASS_AUTO_FOR_NEW					5
#define TIME_DELAY_SHOW_TOPEBOX_ADS			(8*60*60)