/**
* File was generated by animation packager.
*/
#ifndef		_FONT_LV_GOD_BLESSED_I6_H
#define		_FONT_LV_GOD_BLESSED_I6_H


#define		FONT_LV_GOD_BLESSED_I6_NUM_MODULES				12


#define		FONT_LV_GOD_BLESSED_I6_NUM_FRAMES				26


#define		FONT_LV_GOD_BLESSED_I6_NUM_ANIMS				0


#endif