/**
*
*Copyright 2010 Microsoft Corp
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
/**
* Defines default Data Service URL for this proxy class
*/
#define DEFAULT_SERVICE_URL @""


#define DataServiceVersion @"2.0"

#import "ODataObject.h"
#import "ObjectContext.h"
#import "DataServiceQuery.h"
#import "ODataGUID.h"
#import "ODataBool.h"
#import  "mProperties.h"
#import "ODataServiceException.h"


/**
 * @interface:InvitationDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_Invitation : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_InvitationId;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_InvitedBy;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getInvitationId , setter=setInvitationId :) NSString *m_InvitationId;
@property ( nonatomic , retain , getter=getInvitedBy , setter=setInvitedBy :) NSString *m_InvitedBy;

+ (id) CreateInvitationDtoWithid:(NSString *)aID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:InvitedFriendDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_InvitedFriend : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_UserName;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getUserName , setter=setUserName :) NSString *m_UserName;

+ (id) CreateInvitedFriendDtoWithid:(NSString *)aID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:SaveGameDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_SaveGame : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_UserName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Binary
	*/
	NSData *m_Data;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getUserName , setter=setUserName :) NSString *m_UserName;
@property ( nonatomic , retain , getter=getData , setter=setData :)NSData *m_Data;

+ (id) CreateSaveGameDtoWithid:(NSString *)aID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:ServerInfoDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_ServerInfo : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_PstNow;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :)NSNumber *m_ID;
@property ( nonatomic , retain , getter=getPstNow , setter=setPstNow :)NSDate *m_PstNow;

+ (id) CreateServerInfoDtoWithid:(NSNumber *)aID pstnow:(NSDate *)aPstNow;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:StatisticDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_Statistic : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_TotalUsers;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ActiveUsers;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getTotalUsers , setter=setTotalUsers :)NSNumber *m_TotalUsers;
@property ( nonatomic , retain , getter=getActiveUsers , setter=setActiveUsers :)NSNumber *m_ActiveUsers;

+ (id) CreateStatisticDtoWithid:(NSString *)aID totalusers:(NSNumber *)aTotalUsers activeusers:(NSNumber *)aActiveUsers;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:UploadBlobDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_UploadBlob : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_RelativePath;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getRelativePath , setter=setRelativePath :) NSString *m_RelativePath;

+ (id) CreateUploadBlobDtoWithid:(NSString *)aID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:UserDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface ODataObject_User : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_UserName;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :) NSString *m_ID;
@property ( nonatomic , retain , getter=getUserName , setter=setUserName :) NSString *m_UserName;

+ (id) CreateUserDtoWithid:(NSString *)aID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * Container interface TapDefenseContext, Namespace: TapDefense.DataTransferObjects
 */
@interface TapDefenseContext : ObjectContext
{
	 NSString *m_OData_etag;
	 DataServiceQuery *m_Invitations;
	 DataServiceQuery *m_InvitedFriends;
	 DataServiceQuery *m_SaveGames;
	 DataServiceQuery *m_ServerInfos;
	 DataServiceQuery *m_Statistics;
	 DataServiceQuery *m_UploadBlobs;
	 DataServiceQuery *m_LookupUsers;
	
}

@property ( nonatomic , retain , getter=getEtag , setter=setEtag: )NSString *m_OData_etag;
@property ( nonatomic , retain , getter=getInvitations , setter=setInvitations: ) DataServiceQuery *m_Invitations;
@property ( nonatomic , retain , getter=getInvitedFriends , setter=setInvitedFriends: ) DataServiceQuery *m_InvitedFriends;
@property ( nonatomic , retain , getter=getSaveGames , setter=setSaveGames: ) DataServiceQuery *m_SaveGames;
@property ( nonatomic , retain , getter=getServerInfos , setter=setServerInfos: ) DataServiceQuery *m_ServerInfos;
@property ( nonatomic , retain , getter=getStatistics , setter=setStatistics: ) DataServiceQuery *m_Statistics;
@property ( nonatomic , retain , getter=getUploadBlobs , setter=setUploadBlobs: ) DataServiceQuery *m_UploadBlobs;
@property ( nonatomic , retain , getter=getLookupUsers , setter=setLookupUsers: ) DataServiceQuery *m_LookupUsers;

- (id) init;
- (id) initWithUri:(NSString*)anUri credential:(id)acredential;
- (id) invitations;
- (id) invitedfriends;
- (id) savegames;
- (id) serverinfos;
- (id) statistics;
- (id) uploadblobs;
- (id) lookupusers;
- (void) addToInvitations:(id)anObject;
- (void) addToInvitedFriends:(id)anObject;
- (void) addToSaveGames:(id)anObject;
- (void) addToServerInfos:(id)anObject;
- (void) addToStatistics:(id)anObject;
- (void) addToUploadBlobs:(id)anObject;
- (void) addToLookupUsers:(id)anObject;


- (NSString*) getDtoNameFromMetaData: (NSString*)metadata;

@end
